### ISSUE TITLE
Ошибка при запуске YDRPC.exe

### ISSUE THREAD

**Issue by 311time** [Maks1mio/YMusic-DRPC#1]
При запуске ищет дважды py и выдаёт ошибку, при том что python установлен. Windows 11
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/78899658/9fa7e677-ed4a-4ee4-903b-0d64bbc4a54e)

**Comment by Maks1mio** [comment]
Да такая ошибка присутствует и в ближайшем обновлении предоставлю исправление, включая дополнительный функционал.

В промежутке до выпуска обновления, вы можете попробовать решить проблему переустановкой Python и выбором опции (на картинках ниже) в процессе установки. Это должно помочь устранить данную неполадку.
 
![изображение](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/ef51cb0d-985f-4a9b-91df-05754df83aab)

![изображение](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/ffc7abfe-087e-46dc-8ad6-012961571f8f)

В таком случае всё работает)

![изображение](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/4d478014-342f-4a70-9f9c-5021faf133f6)
