### ISSUE TITLE
Не работает RPC

### ISSUE THREAD

**Issue by donelofficial** [Maks1mio/YMusic-DRPC#11]
Скрипт запускается, открывает яндекс.музыку и на этом всё. В дискорде статус не отображается. При этом я разрешил доступ к сети, когда выскочило окно брандмауэра. Версия Яндекс.Музыки: 5.0.14. Это проблема несовместимости (так как скрипт для более старой версии) или в чем может быть причина?

**Comment by Maks1mio** [comment]
Попробуй пока скачать с бета ветки: https://github.com/Maks1mio/YMusic-DRPC/tree/beta
