### ISSUE TITLE
Некорректное отображение исполнителя и названия у самостоятельно загруженных треков

### ISSUE THREAD

**Issue by donelofficial** [Maks1mio/YMusic-DRPC#12]
У загруженных самостоятельно треков на Яндекс.Музыке не отображается исполнитель и название (просто прочерк). При этом время и обложка подгружаются исправно. Это очень странно.
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/111339598/9f99a84b-baa2-4064-8204-254d1fd03592)

**Comment by Maks1mio** [comment]
Ок вечером исправлю походу это после последнего обновления

**Comment by Maks1mio** [comment]
Странно, на бета-версии всё хорошо. 
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/4154e0ae-a4f5-4339-8580-0a1b97877e2b)


Я проверил на последнем коммите beta 🤔

**Comment by Maks1mio** [comment]
Ну при прослушивании локального трека не отображается исполнитель, так что мне неоткуда брать эту информацию.

**Comment by Maks1mio** [comment]
По сути своей я получаю только ту информацию которая отображается

**Comment by Maks1mio** [comment]
Тогда вполне возможно, но сейчас я ушел так что оставлю комментарий когда что-то сделаю попозже

**Comment by Maks1mio** [comment]
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/9425b115-f5e9-4249-9c2b-76b28ac48a13)
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/306ccb30-a489-46e8-9199-bc9df7ce4ae6)
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/63ce0428-f9a5-410a-b154-394d710ba27d)
