### ISSUE TITLE
после обновления программы не показывает название трека в статусе

### ISSUE THREAD

**Issue by plushieward** [Maks1mio/YMusic-DRPC#2]
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/159473280/fbdcd67d-d211-4c14-8b00-62ecaf10d503)

приложение обновилось до версии 5.0.10, включаю любой трек - статус показывает только исполнителя, названия трека просто нет

**Comment by plushieward** [comment]
+ если нажать на open in yandex music, то открывается просто страница исполнителя, а не конкретный трек

**Comment by Maks1mio** [comment]
Ок я возможно знаю в чем проблема, попробую исправить в течении часа

**Comment by Maks1mio** [comment]
![изображение](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/36755cdd-e213-462e-9a20-399ef880f662)

![изображение](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/9f2d8b82-1725-4987-93bb-570fe120b553)
ссылка теперь будет открывать не поиск по названию, а сразу альбом

1820934

**Comment by Maks1mio** [comment]
оно подгрузит обновление после запуска YDRPC.exe
