### ISSUE TITLE
Программа перестала работать

### ISSUE THREAD

**Issue by uFavoriteChair** [Maks1mio/YMusic-DRPC#20]
Вчера всё работало, сегодня запускаю и в консоль выдаются ошибки. Пробовал удалить библиотеки посредством `pip uninstall -r requirements.txt -y` и установить их заново, не помогло. Дальше установил версию скрипта из бета дериктории, тоже не помогло, вообщем не знаю что делать, прикрепляю лог файл, может по нему понятно что я не так сделал.

[yandex_music.log](https://github.com/Maks1mio/YMusic-DRPC/files/14919339/yandex_music.log)

**Comment by Maks1mio** [comment]
Как я понимаю у тебя бета ветка она устаревшая скачай main
"File "C:\Users\grexa\AppData\Local\Programs\**YMusic-DRPC-beta**\YandexDiscordRPC\main.py"

**Comment by Maks1mio** [comment]
Пока точно не могу сказать работает ли она. В данный момент я не за компом.

**Comment by Maks1mio** [comment]
Спасибо ❤️ https://github.com/Maks1mio/YMusic-DRPC/commit/687261066b31a83793b370ff3236330deb46ffbb

в авто обновлении у других обновится файл
