### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by Bluesuma** [Maks1mio/YMusic-DRPC#3]
Всем привет, присутствует проблема со скриптом, выдаёт RPC статус лишь на локальной машине, у других людей не видно.
Протестировано было так:
1. Слова друзей.
2. Лично, зашёл с мобилы, а там нету статуса.

Ждём фикса

**Comment by Bluesuma** [comment]
OS: Win 10
Python: 3.12.1
Порт не занят другими приложениями.

**Comment by Bluesuma** [comment]
Так же нужен апдейт на новую версию

**Comment by Maks1mio** [comment]
Ок ближе к вечеру проверю это и отвечу тут же.

Последние изменения вносил на beta ветке

**Comment by Maks1mio** [comment]
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/50c1d776-8023-438a-95d1-c031361d1953)
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/fcc56908-fac5-4402-ad97-3727f81a5be1)
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/a43e5fd9-d96e-4c26-90b0-9a518b559886)
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/3b6bd721-c8cb-498b-b41f-0577791a9f80)

**Comment by Maks1mio** [comment]
Я проверил и всё работает, думаю что ошибка может быть в другом.

> **может стоит настроить что-то тут**

![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/b2de68b3-38a8-4303-bb76-8436e8cdbdeb)

**Comment by Bluesuma** [comment]
Такет, ну я посмотрел, ничего не пофиксилось, щас скачаю ласт бренч буду тестить

**Comment by Bluesuma** [comment]
5.0.11 поддержка будет?

**Comment by Maks1mio** [comment]
скачай пока бету https://github.com/Maks1mio/YMusic-DRPC/tree/beta

**Comment by Bluesuma** [comment]
Воркает?

**Comment by Maks1mio** [comment]
> Воркает?

точно воркает

**Comment by Maks1mio** [comment]
просто я сейчас занят разработкой альтернативой без использования python
чисто патчить файл https://github.com/Maks1mio/YMusic-DRPC/discussions/6
![image](https://github.com/Maks1mio/YMusic-DRPC/assets/44835662/5f4ced11-b299-4f8b-a854-b27feea8a000)

**Comment by Bluesuma** [comment]
Если нужен TS/JS могу посодействовать, прикольная тема)

**Comment by Maks1mio** [comment]
было бы круто кстати, ибо у меня там дебри 50/50

**Comment by Bluesuma** [comment]
Оно работает)
Спасибо
