### ISSUE TITLE
.exe в репозитории 

### ISSUE THREAD

**Issue by AnimeLore** [Maks1mio/YMusic-DRPC#5]
Думаю будет логичнее перенести .exe файл (и прочее необходимое) в [релизы](https://github.blog/2013-07-02-release-your-software/), оставив в репозитории именно исходный код.

**Comment by AnimeLore** [comment]
![picture](https://github.com/Maks1mio/YMusic-DRPC/assets/43139334/5661234c-860e-45e2-8fb4-7c33b4863481)

**Comment by Maks1mio** [comment]
да было бы не плохо, но я буду ещё кардинально менять кое какие штуки, так что рано пока кидать что-то в релиз

**Comment by Maks1mio** [comment]
> Думаю будет логичнее перенести .exe файл (и прочее необходимое) в [релизы](https://github.blog/2013-07-02-release-your-software/), оставив в репозитории именно исходный код.

Думаю я так и сделаю ибо будет на реакт -> Issues #25 

тема закрыта
