### ISSUE TITLE
requirements.txt вместо отдельного скрипта

### ISSUE THREAD

**Issue by itsLameni** [Maks1mio/YMusic-DRPC#8]
я думаю, что для установки зависимостей скрипта можно использовать возможности pip'а, вместо того, чтобы его вкостыливать в отдельный скрипт (я про install_dependencies.py, если что).

в /YandexDiscordRPC/ поместил бы файл requirements.txt, там вписал бы соответственно зависимости:
```
packaging
websockets
pywinauto
pypresence
requests
psutil
GitPython
```

а в cmd скрипт логично что:

`pip install -r YandexDiscordRPC/requirements.txt` // -r параметр соотвественно для выбора файла requirements.txt

или

`python -m pip install -r YandexDiscordRPC/requirements.txt`

не сказал бы, что это прям важная вещь, но для меня чёт всё равно как-то убого выглядит, что для установки зависимостей юзается отдельный скрипт, когда это можно сделать в pip без отдельных скриптов

**Comment by Maks1mio** [comment]
да спасибо, я так и сделаю

**Comment by itsLameni** [comment]
#9

**Comment by itsLameni** [comment]
это конечно не идеал, но пойдёт

**Comment by Maks1mio** [comment]
да всё гуд, спасибо
